In [220]:
import pandas as pd
import numpy as np
pd.set_option('precision', 0)

In [221]:
import math

In [222]:
user_info=pd.read_csv('random_user_info.csv')
user_info=user_info.rename(columns={'id':'owners_id'})
user_info['location'].fillna('unknown',inplace=True)
#set((user_info.location))
#user_info=user_info[user_info.company.fillna('No Company')]
user_info

,owners_id,bio,company,created_at,disk_usage,followers_count,following_count,last_modified,location,login,name,owned_private_repos,public_repos_count,total_private_gists,total_private_repos
0,236465,NaN,NaN,2010-04-04 00:08:39+00:00,,0,0,"Thu, 09 Apr 2015 19:50:56 GMT",unknown,Goemon,NaN,,2,,
1,184295,NaN,NaN,2010-01-18 01:23:45+00:00,,1,0,"Thu, 09 Apr 2015 19:47:50 GMT",unknown,edward576,NaN,,1,,
2,394022,NaN,NaN,2010-09-10 00:47:44+00:00,,0,0,"Fri, 26 Feb 2016 23:24:59 GMT",unknown,mill-zz,NaN,,0,,
3,492060,NaN,NaN,2010-11-22 16:21:04+00:00,,0,0,"Thu, 09 Apr 2015 20:11:52 GMT",unknown,semazen,NaN,,0,,
4,766502,NaN,NaN,2011-05-03 20:44:50+00:00,,0,0,"Tue, 07 Apr 2015 14:45:59 GMT",unknown,killbotvii,NaN,,0,,
5,960444,NaN,NaN,2011-08-05 03:36:56+00:00,,0,0,"Sat, 27 Feb 2016 00:37:05 GMT",unknown,vis-dbeitler,Daniel Beitler,,0,,
6,185137,NaN,Zero Style,2010-01-19 04:19:10+00:00,,11,15,"Thu, 22 Sep 2016 23:39:10 GMT",Hawai'i,zerostyle,Joshua Stearns,,2,,
7,515485,NaN,NaN,2010-12-08 23:51:32+00:00,,0,0,"Thu, 09 Apr 2015 20:13:43 GMT",unknown,yahi2011,NaN,,0,,
8,161319,NaN,Google,2009-12-03 10:37:00+00:00,,300,15,"Sat, 01 Oct 2016 16:37:19 GMT","New York, NY",crawshaw,David Crawshaw,,24,,
9,943466,NaN,NaN,2011-07-28 02:59:43+00:00,,0,0,"Tue, 07 Apr 2015 14:58:06 GMT",unknown,kick811,NaN,,1,,
10,931133,NaN,NaN,2011-07-21 21:13:31+00:00,,0,1,"Sat, 27 Feb 2016 00:33:20 GMT",unknown,MMRm,MMr,,1,,
11,643834,NaN,NaN,2011-03-01 01:57:46+00:00,,1,0,"Mon, 19 Sep 2016 20:38:15 GMT",Leipzig,BenRoe,Ben,,3,,
12,437098,NaN,NaN,2010-10-12 19:57:35+00:00,,0,0,"Thu, 09 Apr 2015 20:08:08 GMT",unknown,rebel19,NaN,,1,,
13,296001,NaN,NaN,2010-06-03 22:49:45+00:00,,1,0,"Thu, 09 Apr 2015 19:58:29 GMT",unknown,debugger-pl,NaN,,0,,
14,770168,NaN,NaN,2011-05-05 13:51:04+00:00,,2,3,"Wed, 13 Jul 2016 03:54:22 GMT",unknown,toshiotm,Toshiyuki Ohtomo,,26,,
15,575702,NaN,NaN,2011-01-21 03:36:31+00:00,,0,0,"Thu, 09 Apr 2015 20:20:02 GMT",unknown,wmiles,NaN,,0,,
16,818880,NaN,NaN,2011-05-30 14:57:00+00:00,,22,14,"Mon, 26 Sep 2016 08:32:10 GMT","Germany, Munich",wwwdata,Ben Bieker,,21,,
17,644029,NaN,NaN,2011-03-01 04:24:05+00:00,,0,0,"Thu, 09 Apr 2015 20:24:41 GMT",unknown,steve-x,NaN,,0,,
18,150030,NaN,NaN,2009-11-07 06:26:25+00:00,,540,7,"Thu, 26 May 2016 15:43:03 GMT","California, USA",ivaynberg,Igor Vaynberg,,11,,
19,898343,NaN,NaN,2011-07-06 14:37:55+00:00,,0,0,"Mon, 08 Aug 2016 12:31:26 GMT",unknown,soniatuyama,Sonia Tuyama,,0,,
20,661743,NaN,NaN,2011-03-10 10:57:14+00:00,,0,0,"Tue, 18 Mar 2014 11:10:45 GMT",unknown,andorbodenstaff,NaN,,0,,
21,398628,NaN,NaN,2010-09-14 09:08:24+00:00,,0,0,"Thu, 09 Apr 2015 20:05:26 GMT",unknown,Lilio,NaN,,0,,
22,661734,NaN,NaN,2011-03-10 10:54:49+00:00,,5,3,"Wed, 14 Sep 2016 09:18:26 GMT",Germany,andreasbecker,Andreas Becker,,1,,
23,413752,NaN,Carnegie Mellon University,2010-09-24 00:14:38+00:00,,9,5,"Sat, 03 Sep 2016 16:19:54 GMT","Pittsburgh, PA",icaoberg,Ivan E. Cao-Berg,,62,,
24,596631,NaN,NaN,2011-02-02 11:31:09+00:00,,1,1,"Wed, 21 Sep 2016 10:26:40 GMT",unknown,StSimmons,Stephen Simmons,,1,,
25,609570,NaN,NaN,2011-02-09 20:53:43+00:00,,0,0,"Thu, 09 Apr 2015 20:22:19 GMT",unknown,scheratan,NaN,,0,,
26,398355,NaN,NaN,2010-09-14 03:09:40+00:00,,0,0,"Mon, 03 Oct 2016 16:41:06 GMT",Russia,moobzeg,Alexander,,3,,
27,919842,NaN,NaN,2011-07-16 17:25:36+00:00,,0,0,"Tue, 07 Apr 2015 14:56:26 GMT",unknown,felixisgay1,NaN,,0,,
28,670433,NaN,NaN,2011-03-15 06:55:45+00:00,,0,0,"Mon, 05 May 2014 22:16:15 GMT",unknown,simon-fitzpatrick-mincom,Simon FitzPatrick,,0,,
29,855324,NaN,NaN,2011-06-17 00:17:19+00:00,,3,2,"Sat, 27 Feb 2016 00:23:41 GMT",Virginia,Webst3r,Joey Lucas,,0,,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4970,586034,NaN,NaN,2011-01-27 07:03:25+00:00,,0,0,"Fri, 26 Feb 2016 23:49:20 GMT",unknown,bpbrox,Bjørn Brox,,1,,
4971,382324,NaN,NaN,2010-08-31 17:54:47+00:00,,0,0,"Thu, 09 Apr 2015 20:04:15 GMT",unknown,DAL9K,Dru Luce-Edwards,,0,,
4972,179915,NaN,NaN,2010-01-11 10:00:11+00:00,,5,4,"Fri, 30 Sep 2016 21:18:11 GMT",unknown,jguenther,Justin Guenther,,60,,
4973,178997,NaN,NaN,2010-01-09 10:38:50+00:00,,1,0,"Thu, 09 Apr 2015 19:47:32 GMT",Germany,Hermi,Stefan Hermes,,2,,
4974,307778,NaN,NaN,2010-06-17 15:09:25+00:00,,0,0,"Tue, 23 Aug 2016 15:10:51 GMT",unknown,apmxe,NaN,,14,,
4975,388625,NaN,PYNTAIL,2010-09-05 19:50:24+00:00,,0,0,"Wed, 06 Jul 2016 17:03:14 GMT",Santa Monica,kamraan,Kamran Qamar,,0,,
4976,901984,NaN,NaN,2011-07-08 02:01:14+00:00,,0,0,"Thu, 22 Sep 2016 23:41:02 GMT",unknown,steffi2392,Stefanie Ostrowski,,10,,
4977,44494,NaN,NaN,2009-01-06 07:25:39+00:00,,2,0,"Wed, 24 Feb 2016 21:51:00 GMT",unknown,kiranbartakke08,NaN,,2,,
4978,244854,NaN,NaN,2010-04-15 17:34:41+00:00,,0,0,"Wed, 30 Mar 2016 09:51:01 GMT",unknown,rastreador,Manuel Angel Fernandez,,1,,
4979,394076,NaN,NaN,2010-09-10 02:01:19+00:00,,0,0,"Wed, 06 Jul 2016 16:43:55 GMT",unknown,jacobarker,NaN,,0,,
4980,406480,NaN,NaN,2010-09-18 23:22:42+00:00,,11,3,"Sun, 14 Aug 2016 00:19:45 GMT",unknown,johnsmclay,M. Clay Johns,,18,,
4981,634243,NaN,NaN,2011-02-23 16:09:14+00:00,,0,0,"Sat, 01 Oct 2016 19:37:44 GMT",unknown,Krashband,NaN,,2,,
4982,842918,NaN,NaN,2011-06-10 20:13:11+00:00,,0,0,"Sat, 27 Feb 2016 00:22:06 GMT",unknown,cswelker,NaN,,0,,
4983,269145,NaN,NaN,2010-05-07 00:30:29+00:00,,0,0,"Thu, 09 Apr 2015 19:56:40 GMT",unknown,arcadiomccreedan312,NaN,,0,,
4984,117511,NaN,NaN,2009-08-20 13:46:28+00:00,,1,1,"Mon, 29 Feb 2016 19:29:22 GMT",unknown,kennylin0309,NaN,,0,,
4985,17338,NaN,NaN,2008-07-17 12:53:44+00:00,,2,0,"Fri, 26 Feb 2016 22:36:55 GMT",unknown,therealtroll,NaN,,1,,
4986,547377,NaN,Rational Interaction,2011-01-04 18:22:04+00:00,,3,0,"Tue, 27 Sep 2016 15:47:30 GMT","Seattle, WA",AdamPflug,Adam Pflug,,9,,
4987,198118,NaN,NaN,2010-02-06 00:25:48+00:00,,4,3,"Fri, 26 Feb 2016 23:00:30 GMT",unknown,djseika,Alejo Fernandez,,0,,
4988,296100,NaN,NaN,2010-06-04 01:44:35+00:00,,1,0,"Fri, 26 Feb 2016 23:12:38 GMT",unknown,Yonggon-Cho,NaN,,1,,
4989,310064,NaN,EF Education First,2010-06-20 16:45:12+00:00,,8,13,"Fri, 09 Sep 2016 04:39:38 GMT",Hong Kong,ben1one,Ben Suen,,14,,
4990,683786,Software Developer from @zalando,Owl Unit,2011-03-22 12:33:19+00:00,,28,10,"Tue, 04 Oct 2016 13:47:45 GMT",Berlin,Otann,Anton Chebotaev,,24,,
4991,898777,NaN,NaN,2011-07-06 17:50:14+00:00,,0,0,"Fri, 27 May 2016 20:31:01 GMT",unknown,idsme,Ids,,5,,
4992,874584,"I'm a freelance WordPress theme developer, sno...",Freelance WordPress Dev,2011-06-25 02:04:43+00:00,,24,21,"Tue, 07 Jun 2016 00:07:47 GMT","Melbourne, Australia",AaronRutley,Aaron Rutley,,18,,
4993,629249,NaN,NaN,2011-02-21 04:17:05+00:00,,1,0,"Tue, 09 Aug 2016 20:32:00 GMT",unknown,adiro,Ab Diro,,4,,
4994,987984,NaN,NaN,2011-08-18 06:45:58+00:00,,1,0,"Sat, 27 Feb 2016 00:40:35 GMT",unknown,activecubes,Satyan Warrier,,0,,
4995,688031,NaN,NaN,2011-03-24 10:40:42+00:00,,0,0,"Sat, 27 Feb 2016 00:02:16 GMT",unknown,hostrm,NaN,,1,,
4996,494591,NaN,NaN,2010-11-24 08:15:11+00:00,,0,0,"Fri, 26 Feb 2016 23:37:44 GMT",unknown,fatwa,NaN,,0,,
4997,280122,NaN,NaN,2010-05-18 09:19:01+00:00,,0,0,"Thu, 09 Apr 2015 19:57:24 GMT",unknown,andyjay,NaN,,0,,
4998,790601,NaN,NaN,2011-05-16 09:21:20+00:00,,0,2,"Wed, 17 Feb 2016 13:18:23 GMT",unknown,Benoit-Thierry,NaN,,1,,
4999,820630,NaN,NaN,2011-05-31 12:43:35+00:00,,10,7,"Thu, 11 Aug 2016 05:44:32 GMT",Philippines,pixelsquare,Anthony Ganzon,,26,,

In [223]:
#pd.read_csv('sampled_data_user_list.csv')

In [224]:
users_rep=pd.read_json('pretty_repo_list6.json')
repo_owner=pd.DataFrame(users_rep['owner'])
#Reading the json object available in the field owner and appending it to list
owner=[]
len_repo=len(repo_owner)
for i in range(0,len_repo):
    owner.append((repo_owner['owner'][i]))

In [225]:
owner= pd.DataFrame(owner)
owner=owner[['id','login']]
users_rep['owners_id']=pd.Series(owner['id'])
users_rep['owners_name']=pd.Series(owner['login'])

In [226]:
world_cities=pd.read_csv('simplemaps-worldcities-basic.csv')
world_cities.columns

#world_cities.loc[world_cities['city'] == 'Po']

Index(['city', 'city_ascii', 'lat', 'lng', 'pop', 'country', 'iso2', 'iso3',
       'province'],
      dtype='object')

In [172]:
foo = lambda x: pd.Series([i for i in (x.split(','))])
split_df = user_info['location'].apply(foo)
split_df=split_df.rename(columns={0:'city'})
split_df=pd.DataFrame(split_df['city'])

In [227]:
user_info.drop('location', axis=1, inplace=True)
user_info=pd.concat([user_info,split_df],axis=1)
#user_info

In [174]:
user_info_location_coordinates=pd.merge(user_info,world_cities,)

In [175]:
user_info_location_coordinates.rename(columns={'lat':'latitude','lng':'longitude'},inplace=True)

In [176]:
user_info_location_coordinates

,owners_id,bio,company,created_at,disk_usage,followers_count,following_count,last_modified,login,name,...,total_private_repos,city,city_ascii,latitude,longitude,pop,country,iso2,iso3,province
0,161319,NaN,Google,2009-12-03 10:37:00+00:00,,300,15,"Sat, 01 Oct 2016 16:37:19 GMT",crawshaw,David Crawshaw,...,,New York,New York,41,-74,1e+07,United States of America,US,USA,New York
1,52901,NaN,Automattic,2009-02-09 02:34:07+00:00,,21,0,"Fri, 07 Oct 2016 14:59:36 GMT",bazza,Barry Abrahamson,...,,New York,New York,41,-74,1e+07,United States of America,US,USA,New York
2,560733,NaN,CBS Local Digital Media Group,2011-01-12 18:25:24+00:00,,18,49,"Mon, 29 Aug 2016 15:07:24 GMT",danieljstwrt,Daniel Stewart,...,,New York,New York,41,-74,1e+07,United States of America,US,USA,New York
3,371493,NaN,"Global Data 360, Inc.",2010-08-21 03:12:03+00:00,,5,5,"Mon, 05 Sep 2016 14:17:00 GMT",garyrusso,Gary Russo,...,,New York,New York,41,-74,1e+07,United States of America,US,USA,New York
4,861849,NaN,Intrepid Pursuits,2011-06-20 14:21:06+00:00,,2,1,"Mon, 12 Sep 2016 18:56:43 GMT",cprime,Colden Prime,...,,New York,New York,41,-74,1e+07,United States of America,US,USA,New York
5,62430,NaN,NaN,2009-03-11 15:15:32+00:00,,28,1,"Fri, 26 Aug 2016 10:28:20 GMT",pedroha,Pedro Ha,...,,New York,New York,41,-74,1e+07,United States of America,US,USA,New York
6,701892,NaN,Quick Extender Pro Inc.,2011-03-31 15:59:50+00:00,,0,0,"Mon, 23 Nov 2015 22:18:52 GMT",QuickExtenderPro,QuickExtender Pro,...,,New York,New York,41,-74,1e+07,United States of America,US,USA,New York
7,578638,NaN,Pc2Mac,2011-01-22 23:56:25+00:00,,0,0,"Thu, 09 Apr 2015 20:20:13 GMT",eddyyla,eddyyla,...,,New York,New York,41,-74,1e+07,United States of America,US,USA,New York
8,947644,Lead .Net developer with over the 8 years expe...,NaN,2011-07-29 21:35:54+00:00,,1,18,"Fri, 26 Aug 2016 16:08:12 GMT",vaklove,Vik,...,,New York,New York,41,-74,1e+07,United States of America,US,USA,New York
9,6746,NaN,NaN,2008-04-11 19:12:52+00:00,,4,0,"Wed, 11 May 2016 20:34:18 GMT",georgezhao,george zhao,...,,New York,New York,41,-74,1e+07,United States of America,US,USA,New York
10,58860,NaN,Google,2009-02-28 13:34:01+00:00,,100,4,"Sat, 01 Oct 2016 02:27:07 GMT",MarkLodato,Mark Lodato,...,,New York,New York,41,-74,1e+07,United States of America,US,USA,New York
11,299006,NaN,Reducify,2010-06-07 16:15:46+00:00,,1,0,"Fri, 26 Feb 2016 23:13:00 GMT",Reducify,Reducify!,...,,New York,New York,41,-74,1e+07,United States of America,US,USA,New York
12,244622,NaN,NaN,2010-04-15 13:02:17+00:00,,0,0,"Sun, 02 Oct 2016 10:44:10 GMT",KaplanTestPrep,Kaplan Test Prep,...,,New York,New York,41,-74,1e+07,United States of America,US,USA,New York
13,279687,NaN,NaN,2010-05-17 21:18:57+00:00,,0,0,"Sun, 11 Sep 2016 09:59:06 GMT",charitywater,charity: water,...,,New York,New York,41,-74,1e+07,United States of America,US,USA,New York
14,112594,NaN,"Imagine Easy Solutions, LLC",2009-08-06 15:48:42+00:00,,8,0,"Fri, 30 Sep 2016 10:27:38 GMT",darshanbib,Darshan Somashekar,...,,New York,New York,41,-74,1e+07,United States of America,US,USA,New York
15,290158,NaN,NaN,2010-05-28 18:54:14+00:00,,5,4,"Mon, 12 Sep 2016 16:39:06 GMT",dgame84,Dmitry Gimzelberg,...,,New York,New York,41,-74,1e+07,United States of America,US,USA,New York
16,255952,NaN,The Tandem Group,2010-04-28 16:37:30+00:00,,3,5,"Mon, 26 Sep 2016 16:11:45 GMT",itschriswilliams,Christopher Williams,...,,New York,New York,41,-74,1e+07,United States of America,US,USA,New York
17,30181,NaN,"On2 Technologies, Inc.",2008-10-21 17:26:40+00:00,,8,2,"Thu, 09 Apr 2015 19:39:44 GMT",flixcloud,On2 Flix Cloud,...,,New York,New York,41,-74,1e+07,United States of America,US,USA,New York
18,8481,NaN,NaN,2008-04-25 13:58:35+00:00,,34,0,"Tue, 30 Aug 2016 13:34:45 GMT",saml,saml,...,,New York,New York,41,-74,1e+07,United States of America,US,USA,New York
19,93425,NaN,NaN,2009-06-09 04:11:38+00:00,,9,2,"Fri, 26 Feb 2016 22:47:08 GMT",jimyi,Jim Yi,...,,New York,New York,41,-74,1e+07,United States of America,US,USA,New York
20,214996,NaN,Genius,2010-03-03 20:56:11+00:00,,0,0,"Fri, 30 Sep 2016 18:17:57 GMT",kevosauce,Kevin,...,,New York,New York,41,-74,1e+07,United States of America,US,USA,New York
21,643834,NaN,NaN,2011-03-01 01:57:46+00:00,,1,0,"Mon, 19 Sep 2016 20:38:15 GMT",BenRoe,Ben,...,,Leipzig,Leipzig,51,12,5e+05,Germany,DE,DEU,Sachsen
22,413752,NaN,Carnegie Mellon University,2010-09-24 00:14:38+00:00,,9,5,"Sat, 03 Sep 2016 16:19:54 GMT",icaoberg,Ivan E. Cao-Berg,...,,Pittsburgh,Pittsburgh,40,-80,2e+06,United States of America,US,USA,Pennsylvania
23,471832,NaN,CMU,2010-11-08 03:20:52+00:00,,1,1,"Sat, 24 Sep 2016 05:44:55 GMT",fishbone,Yi Cheng,...,,Pittsburgh,Pittsburgh,40,-80,2e+06,United States of America,US,USA,Pennsylvania
24,133801,NaN,Decimus Software,2009-10-01 16:29:14+00:00,,18,0,"Thu, 11 Aug 2016 01:32:01 GMT",bdrister,Benjamin Rister,...,,Pittsburgh,Pittsburgh,40,-80,2e+06,United States of America,US,USA,Pennsylvania
25,255925,NaN,NaN,2010-04-28 16:08:29+00:00,,1,0,"Thu, 25 Aug 2016 20:48:46 GMT",TheCodingYeezus,Michael Chislow,...,,Pittsburgh,Pittsburgh,40,-80,2e+06,United States of America,US,USA,Pennsylvania
26,596039,NaN,University of Pittsburgh,2011-02-02 02:27:17+00:00,,3,9,"Tue, 20 Sep 2016 20:48:15 GMT",bpasquini,Brian Pasquini,...,,Pittsburgh,Pittsburgh,40,-80,2e+06,United States of America,US,USA,Pennsylvania
27,855324,NaN,NaN,2011-06-17 00:17:19+00:00,,3,2,"Sat, 27 Feb 2016 00:23:41 GMT",Webst3r,Joey Lucas,...,,Virginia,Virginia,48,-93,9e+03,United States of America,US,USA,Minnesota
28,66289,NaN,NaN,2009-03-24 03:01:28+00:00,,12,1,"Sun, 18 Sep 2016 01:28:15 GMT",stith,Matt Stith,...,,Virginia,Virginia,48,-93,9e+03,United States of America,US,USA,Minnesota
29,128240,NaN,@Automattic,2009-09-17 18:46:59+00:00,,39,52,"Fri, 23 Sep 2016 19:07:53 GMT",georgeh,George Hotelling,...,,Detroit,Detroit,42,-83,3e+06,United States of America,US,USA,Michigan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1058,865177,NaN,NaN,2011-06-21 19:46:54+00:00,,2,1,"Thu, 06 Oct 2016 15:54:04 GMT",eduffy,Edward Duffy,...,,Greenville,Greenville,36,-77,8e+04,United States of America,US,USA,North Carolina
1059,574259,NaN,https://angel.co/trucktrack,2011-01-20 10:12:47+00:00,,3,23,"Thu, 22 Sep 2016 19:26:22 GMT",marko-ciric,Marko Ciric,...,,Belgrade,Belgrade,45,20,1e+06,Serbia,RS,SRB,Grad Beograd
1060,21077,NaN,NaN,2008-08-18 21:39:55+00:00,,3,0,"Fri, 26 Feb 2016 22:37:26 GMT",NathanaelB,Nathanael Boehm,...,,Canberra,Canberra,-35,149,3e+05,Australia,AU,AUS,Australian Capital Territory
1061,892024,NaN,NaN,2011-07-03 18:33:49+00:00,,0,9,"Sat, 24 Sep 2016 20:31:45 GMT",stevemustafa,Steve Mustafa aka Mufasaa,...,,Calgary,Calgary,51,-114,1e+06,Canada,CA,CAN,Alberta
1062,765319,NaN,"Android Engineer @ Musixmatch, Android GDE",2011-05-03 09:40:33+00:00,,82,39,"Fri, 30 Sep 2016 14:50:05 GMT",dextorer,Sebastiano Gottardo,...,,Bologna,Bologna,45,11,4e+05,Italy,IT,ITA,Emilia-Romagna
1063,33799,NaN,NaN,2008-11-11 10:31:21+00:00,,5,0,"Fri, 23 Sep 2016 08:59:26 GMT",pascaln,Pascal Naef,...,,Luzern,Luzern,47,8,2e+05,Switzerland,CH,CHE,Lucerne
1064,568328,NaN,GenITeam,2011-01-17 05:27:23+00:00,,0,0,"Fri, 26 Feb 2016 23:47:05 GMT",numan-geniteam,Numan Tariq,...,,Lahore,Lahore,32,74,6e+06,Pakistan,PK,PAK,Punjab
1065,1464,NaN,NaN,2008-02-28 07:08:07+00:00,,10,5,"Tue, 07 Jun 2016 19:23:26 GMT",Oblomov,NaN,...,,Catania,Catania,37,15,5e+05,Italy,IT,ITA,Sicily
1066,168691,NaN,NaN,2009-12-16 23:55:40+00:00,,1,0,"Tue, 09 Aug 2016 13:43:41 GMT",HellSpider,Ricardo Ferreira,...,,Porto,Porto,41,-9,8e+05,Portugal,PT,PRT,Porto
1067,524259,NaN,Ionata Digital,2010-12-15 12:39:15+00:00,,18,43,"Fri, 16 Sep 2016 11:25:20 GMT",avioli,Evo Stamatov,...,,Hobart,Hobart,-43,147,6e+04,Australia,AU,AUS,Tasmania
1068,518265,NaN,NaN,2010-12-10 19:47:05+00:00,,1,0,"Wed, 06 Jul 2016 18:06:33 GMT",JeffCren,Jeff Crenshaw,...,,Richmond,Richmond,-34,151,1e+04,Australia,AU,AUS,New South Wales
1069,518265,NaN,NaN,2010-12-10 19:47:05+00:00,,1,0,"Wed, 06 Jul 2016 18:06:33 GMT",JeffCren,Jeff Crenshaw,...,,Richmond,Richmond,-21,143,3e+02,Australia,AU,AUS,Queensland
1070,518265,NaN,NaN,2010-12-10 19:47:05+00:00,,1,0,"Wed, 06 Jul 2016 18:06:33 GMT",JeffCren,Jeff Crenshaw,...,,Richmond,Richmond,40,-85,4e+04,United States of America,US,USA,Indiana
1071,518265,NaN,NaN,2010-12-10 19:47:05+00:00,,1,0,"Wed, 06 Jul 2016 18:06:33 GMT",JeffCren,Jeff Crenshaw,...,,Richmond,Richmond,38,-77,6e+05,United States of America,US,USA,Virginia
1072,203614,NaN,"NC Software, Inc.",2010-02-14 21:15:54+00:00,,2,15,"Wed, 10 Aug 2016 18:38:28 GMT",neal007,Neal Culiner,...,,Richmond,Richmond,-34,151,1e+04,Australia,AU,AUS,New South Wales
1073,203614,NaN,"NC Software, Inc.",2010-02-14 21:15:54+00:00,,2,15,"Wed, 10 Aug 2016 18:38:28 GMT",neal007,Neal Culiner,...,,Richmond,Richmond,-21,143,3e+02,Australia,AU,AUS,Queensland
1074,203614,NaN,"NC Software, Inc.",2010-02-14 21:15:54+00:00,,2,15,"Wed, 10 Aug 2016 18:38:28 GMT",neal007,Neal Culiner,...,,Richmond,Richmond,40,-85,4e+04,United States of America,US,USA,Indiana
1075,203614,NaN,"NC Software, Inc.",2010-02-14 21:15:54+00:00,,2,15,"Wed, 10 Aug 2016 18:38:28 GMT",neal007,Neal Culiner,...,,Richmond,Richmond,38,-77,6e+05,United States of America,US,USA,Virginia
1076,225712,I write code and jump from airplanes,Valu Digital Oy,2010-03-18 22:11:41+00:00,,218,48,"Sun, 18 Sep 2016 16:20:39 GMT",epeli,Esa-Matti Suuronen,...,,Jyväskylä,Jyvaskyla,62,26,9e+04,Finland,FI,FIN,Central Finland
1077,621957,NaN,Invert Game Studios LLC,2011-02-16 20:21:04+00:00,,12,3,"Mon, 03 Oct 2016 13:01:02 GMT",micahosborne,Micah Osborne,...,,Florida,Florida,-34,-56,3e+04,Uruguay,UY,URY,Florida
1078,185686,NaN,CEF,2010-01-19 20:31:03+00:00,,2,5,"Wed, 27 Jan 2016 23:11:34 GMT",welber10,Welber Gouveia,...,,Goiania,Goiania,-17,-49,2e+06,Brazil,BR,BRA,Goiás
1079,497527,NaN,NaN,2010-11-26 07:59:13+00:00,,4,0,"Sat, 04 Jun 2016 08:14:12 GMT",pierangelo,Pierangelo Mancusi,...,,Roma,Roma,-27,149,5e+03,Australia,AU,AUS,Queensland
1080,805398,NaN,Axion Commerce,2011-05-23 15:11:17+00:00,,7,0,"Fri, 27 May 2016 20:25:29 GMT",nathanfirth,Nathan Firth,...,,San Marcos,San Marcos,15,-92,3e+04,Guatemala,GT,GTM,San Marcos
1081,805398,NaN,Axion Commerce,2011-05-23 15:11:17+00:00,,7,0,"Fri, 27 May 2016 20:25:29 GMT",nathanfirth,Nathan Firth,...,,San Marcos,San Marcos,30,-98,6e+04,United States of America,US,USA,Texas
1082,834159,NaN,RG Sistemas,2011-06-07 02:49:37+00:00,,6,9,"Fri, 16 Sep 2016 14:09:42 GMT",acmon,Ácmon Soares,...,,Nova Friburgo,Nova Friburgo,-22,-43,2e+05,Brazil,BR,BRA,Rio de Janeiro
1083,673860,NaN,Tam Tam,2011-03-16 20:21:35+00:00,,1,4,"Sat, 27 Feb 2016 00:00:27 GMT",elmarkou,Elmar Kouwenhoven,...,,The Hague,The Hague,52,4,1e+06,Netherlands,NL,NLD,Zuid-Holland
1084,610248,NaN,NaN,2011-02-10 04:58:10+00:00,,12,3,"Sun, 12 Jun 2016 20:08:02 GMT",phoxicle,Christine Gerpheide,...,,The Hague,The Hague,52,4,1e+06,Netherlands,NL,NLD,Zuid-Holland
1085,152548,NaN,NaN,2009-11-12 22:23:24+00:00,,2,0,"Sat, 23 Jul 2016 03:18:22 GMT",boulter,Jeff Boulter,...,,Lexington,Lexington,38,-85,2e+05,United States of America,US,USA,Kentucky
1086,33300,NaN,NaN,2008-11-08 01:12:56+00:00,,2,0,"Fri, 26 Feb 2016 22:39:06 GMT",DXBoter,K. A. AlZaabi,...,,Dubai,Dubai,25,55,1e+06,United Arab Emirates,AE,ARE,Dubay
1087,54052,NaN,Jobber,2009-02-12 20:40:51+00:00,,16,19,"Sat, 17 Sep 2016 09:50:41 GMT",forrest,Forrest Zeisler,...,,Edmonton,Edmonton,54,-113,9e+05,Canada,CA,CAN,Alberta

# 1) Company uses which languages and which company has highest stargazers which will show the popularity of Company and Language used within that company.

In [177]:
frame1 = user_info[['owners_id','company']]
frame2= users_rep[['owners_id','language','stargazers_count']]

In [178]:

d=list(set(frame2['owners_id']))

In [179]:
frame1=frame1[frame1['owners_id'].isin(d)]

stargazers_count_company=pd.merge(left=frame2,right=frame1, how='left', left_on='owners_id', right_on='owners_id')

In [180]:
stargazers_count_company=stargazers_count_company[['owners_id', 'company', 'language', 'stargazers_count']]

In [181]:
stargazers_count_company=stargazers_count_company.groupby(['company','language']).agg({'stargazers_count':np.count_nonzero})

In [182]:
stargazers_count_company=stargazers_count_company.sort_values(by='stargazers_count',ascending=False).reset_index(drop=False)

stargazers_count_company=stargazers_count_company.head(15).reset_index(drop=True)
stargazers_count_company.to_csv('stargazers_count_company.csv',index=None)

In [183]:
stargazers_count_company

,company,language,stargazers_count
0,Mad Science,JavaScript,38
1,Valu Digital Oy,JavaScript,28
2,Google,Python,27
3,Independent contractor,JavaScript,21
4,DroniX Dev Team,C,20
5,Selesti,PHP,19
6,Phonemaster Communications,Ruby,18
7,Basho Technologies,Ruby,15
8,"Available (Berlin, Hamburg, Athens, wordwide)",PHP,14
9,Rent.com,Perl,14
10,@beyond-agentur & @GFZM,JavaScript,14
11,Ars Machina Tecnologia da Informação Ltda.,Java,14
12,UC San Diego,Haskell,14
13,Continuity Control,Ruby,14
14,,JavaScript,14

### 2)Which Location uses how many languages and which is mostly used language within that region. (which shows popularity of language within specific regions)

In [184]:
frame1 = user_info_location_coordinates[['owners_id','city','latitude','longitude','iso2','iso3']]
frame2= users_rep[['owners_id','language','id']]

In [185]:
d=list(set(frame2['owners_id']))


frame1=frame1[frame1['owners_id'].isin(d)]

Languages_location = pd.merge(left=frame2,right=frame1, how='left', left_on='owners_id', right_on='owners_id')
#Languages_location.drop_duplicates()

In [186]:
#import collections
Languages_location=Languages_location.groupby(['city','latitude','longitude','iso2','iso3']).language.value_counts()
#Languages_location
#Languages_location=Languages_location.dropna()
#Languages_location_count=Languages_location.drop_duplicates()
#Languages_location_count
#Languages_location_count.reset_index(drop=True)

In [187]:
#import collections
#Languages_location=Languages_location.groupby(['location']).language.value_counts().unstack().fillna(0)
#Languages_location
#Languages_location=Languages_location.dropna()
#Languages_location_count=Languages_location.drop_duplicates()
#Languages_location_count
#Languages_location_count.reset_index(drop=True)

In [188]:
Languages_location=Languages_location.to_frame()

Languages_location=Languages_location.fillna(0)

In [189]:
Languages_location =Languages_location.sort_values(by='language',ascending=False)
Languages_location=Languages_location.rename(columns={'language':'language_count'})

Languages_location=Languages_location.reset_index(drop=False)
#Languages_location.to_csv('/home/shirz/Desktop/Final files for Descriptive/Languages_location.csv')

In [190]:
(Languages_location[0:1000]).to_csv('lang_loc.csv')

# 3) Countries which are most popular (having large no. stargazers)uses mostly which languages which gives (popularity of region and language)

In [191]:
frame1 = user_info_location_coordinates[['owners_id','city','latitude','longitude','iso3']]
frame2= users_rep[['owners_id','language','stargazers_count']]

In [192]:
d=list(set(frame2['owners_id']))

frame1=frame1[frame1['owners_id'].isin(d)]

pop_countries_stargazers=pd.merge(left=frame2,right=frame1, how='right', left_on='owners_id', right_on='owners_id')

In [193]:
pop_countries_stargazers=pop_countries_stargazers.groupby(['city','language','latitude','longitude','iso3']).agg({'stargazers_count': sum}).reset_index()

In [194]:
pop_countries_stargazers=pop_countries_stargazers.sort_values(by='stargazers_count',ascending=False).reset_index(drop=True)

In [195]:
pop_countries_stargazers = pop_countries_stargazers.drop_duplicates('city')
pop_countries_stargazers.to_csv('pop_countries_stargazers.csv')

In [196]:
(pop_countries_stargazers.drop_duplicates('city')).to_csv('file1.csv')

# 4) Companies with highest repositories and language is been used in that company which will show which company is making more projects and on which language.

In [206]:
frame1 = user_info_location_coordinates[['company','owners_id','city','latitude','longitude','iso2','iso3']]
frame2= users_rep[['owners_id','language','id']]

In [207]:
d=list(set(frame2['owners_id']))

frame1=frame1[frame1['owners_id'].isin(d)]

company_Languages_repos=pd.merge(left=frame2,right=frame1, how='left', left_on='owners_id', right_on='owners_id')

In [205]:
company_Languages_repos=company_Languages_repos.groupby(['company','language']).agg({'id':np.count_nonzero})

In [200]:
company_Languages_repos=company_Languages_repos.rename(columns={'id':'Repositories_count'})

In [201]:
company_Languages_repos=company_Languages_repos.sort_values(by='Repositories_count',ascending=False).reset_index(drop=False)

In [202]:
company_Languages_repos.to_csv('company_Languages_repos.csv')

In [49]:
company_Languages_repos

                         company      language  Repositories_count
0                      Atlassian       Clojure                  64
1                       Rent.com          Perl                  52
2                         Meraki    JavaScript                  52
3                Valu Digital Oy    JavaScript                  52
4      One Red Dog Media Pty Ltd   Objective-C                  44
5                       @stampr     JavaScript                  44
6                    Jinlabs Ltd    JavaScript                  42
7                  TBODA Pty Ltd            C#                  42
8               LARION Computing          Ruby                  42
9                                  JavaScript                  38
10             Aloudly Education    JavaScript                  38
11        Independent contractor    JavaScript                  36
12                     @AblePear             C                  32
13                     Atlassian    JavaScript                  32
14                Ionata Digital    JavaScript                  30
15            Basho Technologies          Ruby                  30
16               Financial Times    JavaScript                  30
17    Sands Consulting Sdn. Bhd.    JavaScript                  30
18                       Onefeat          Ruby                  30
19                       Tascent       Verilog                  30
20    Sands Consulting Sdn. Bhd.           PHP                  30
21     Plecco Technologies, Inc.          Ruby                  28
22                      Zenefits          Ruby                  28
23                           W+K    JavaScript                  27
24                       Espians            Go                  27
25                  BuilderTREND          Java                  26
26                        Heroku          Ruby                  26
27             Happy Nerd Shirts    JavaScript                  26
28       Localize, Techstars, YC    JavaScript                  26
29            http://cutbot.net/          Perl                  25
...                          ...           ...                 ...
1431                   GameLearn          Ruby                   1
1432            Freeflow Digital           PHP                   1
1433                 Fictive Kin        Python                   1
1434                 Fictive Kin   Objective-C                   1
1435                Systemsmiths          HTML                   1
1436           Templateninja.net  ActionScript                   1
1437           MIT Class of 2018          VimL                   1
1438           MIT Class of 2018           C++                   1
1439                EPAM Systems         Shell                   1
1440                 Logic Squad          XSLT                   1
1441             Ennova Research    JavaScript                   1
1442            Le Blog de Genma           PHP                   1
1443             Ennova Research         Shell                   1
1444                     NthCode           CSS                   1
1445                    Ericsson             C                   1
1446                    Ericsson           C++                   1
1447                Systemsmiths            F#                   1
1448            Studio Sugarfree  ActionScript                   1
1449                    Ericsson           CSS                   1
1450            Le Blog de Genma    JavaScript                   1
1451              Sugoi Software           PHP                   1
1452                    Ericsson          Java                   1
1453                    Ericsson          Rust                   1
1454                   Subito.it          VimL                   1
1455                   Subito.it         Swift                   1
1456                     Escenic          HTML                   1
1457            Studio Sugarfree          Ruby                   1
1458                     Escenic           TeX                   1
1459                LINE Fukuoka        Python                   1
1460                     NthCode             C                   1

[1461 rows x 3 columns]

# 5) Which countries have highest no. of respositories and in which language which will show which country is   making more projects and on which language.

In [216]:
frame1 = user_info_location_coordinates[['owners_id','city','iso2','iso3']]
frame2= users_rep[['owners_id','language','id']]

In [217]:
d=list(set(frame2['owners_id']))

frame1=frame1[frame1['owners_id'].isin(d)]

#Location_Languages_repos=pd.merge(left=frame2,right=frame1, how='left', left_on='owners_id', right_on='owners_id')

In [218]:
frame1

      owners_id           city iso2 iso3
0        161319       New York   US  USA
1         52901       New York   US  USA
2        560733       New York   US  USA
3        371493       New York   US  USA
4        861849       New York   US  USA
5         62430       New York   US  USA
8        947644       New York   US  USA
9          6746       New York   US  USA
10        58860       New York   US  USA
11       299006       New York   US  USA
12       244622       New York   US  USA
13       279687       New York   US  USA
14       112594       New York   US  USA
16       255952       New York   US  USA
17        30181       New York   US  USA
18         8481       New York   US  USA
19        93425       New York   US  USA
20       214996       New York   US  USA
21       643834        Leipzig   DE  DEU
22       413752     Pittsburgh   US  USA
23       471832     Pittsburgh   US  USA
24       133801     Pittsburgh   US  USA
25       255925     Pittsburgh   US  USA
26       596039     Pittsburgh   US  USA
28        66289       Virginia   US  USA
29       128240        Detroit   US  USA
30       827767        Detroit   US  USA
31       301388       Portland   AU  AUS
32       301388       Portland   US  USA
33       301388       Portland   US  USA
...         ...            ...  ...  ...
1047      45921       Brighton   GB  GBR
1049     545339        Norwich   GB  GBR
1050     164472   Grand Rapids   US  USA
1052     589801        Tbilisi   GE  GEO
1053     141195   Fort Collins   US  USA
1054      82532           Kiev   UA  UKR
1055     865177     Greenville   LR  LBR
1056     865177     Greenville   US  USA
1057     865177     Greenville   US  USA
1058     865177     Greenville   US  USA
1059     574259       Belgrade   RS  SRB
1060      21077       Canberra   AU  AUS
1061     892024        Calgary   CA  CAN
1062     765319        Bologna   IT  ITA
1063      33799         Luzern   CH  CHE
1064     568328         Lahore   PK  PAK
1065       1464        Catania   IT  ITA
1067     524259         Hobart   AU  AUS
1076     225712      Jyväskylä   FI  FIN
1077     621957        Florida   UY  URY
1078     185686        Goiania   BR  BRA
1079     497527           Roma   AU  AUS
1080     805398     San Marcos   GT  GTM
1081     805398     San Marcos   US  USA
1082     834159  Nova Friburgo   BR  BRA
1083     673860      The Hague   NL  NLD
1084     610248      The Hague   NL  NLD
1085     152548      Lexington   US  USA
1086      33300          Dubai   AE  ARE
1087      54052       Edmonton   CA  CAN

[931 rows x 4 columns]

In [210]:
#Location_Languages_repos =Location_Languages_repos.groupby(['city','language','iso2','iso3']).agg({'id':np.count_nonzero})

In [211]:

#Location_Languages_repos=Location_Languages_repos.rename(columns={'id':'Repositories_Count'})

In [212]:
#Location_Languages_repos = Location_Languages_repos.dropna()

In [213]:
Location_Languages_repos = Location_Languages_repos.drop_duplicates()

In [214]:
Location_Languages_repos

       owners_id     language        id      city iso2 iso3
0         236465         None    593742       NaN  NaN  NaN
1         236465           Go    593693       NaN  NaN  NaN
2         184295         None    476841       NaN  NaN  NaN
3         185137   JavaScript  42210424       NaN  NaN  NaN
4         185137   JavaScript  57074597       NaN  NaN  NaN
5         161319           Go  28539413  New York   US  USA
6         161319           Go  19331464  New York   US  USA
7         161319           Go  25886137  New York   US  USA
8         161319           Go  51116256  New York   US  USA
9         161319           Go  57044534  New York   US  USA
10        161319           Go  19209086  New York   US  USA
11        161319           Go  26715715  New York   US  USA
12        161319           Go  38956750  New York   US  USA
13        161319           Go  17315733  New York   US  USA
14        161319         None  23586314  New York   US  USA
15        161319           Go  27606821  New York   US  USA
16        161319           Go  32553456  New York   US  USA
17        161319           Go  28349747  New York   US  USA
18        161319           Go  44833352  New York   US  USA
19        161319           Go  29684525  New York   US  USA
20        161319           Go  10772891  New York   US  USA
21        161319        Scala    410653  New York   US  USA
22        161319          C++    661210  New York   US  USA
23        161319         None  30826807  New York   US  USA
24        161319           Go  26926222  New York   US  USA
25        161319         None    393969  New York   US  USA
26        161319           Go  29072837  New York   US  USA
27        161319         None    401909  New York   US  USA
28        161319            C    453951  New York   US  USA
29        943466         None   2402892       NaN  NaN  NaN
...          ...          ...       ...       ...  ...  ...
34979     629249         Ruby  23903916       NaN  NaN  NaN
34980     629249  Objective-C  23898293       NaN  NaN  NaN
34981     688031         None   1520449       NaN  NaN  NaN
34982     790601         None   1754530       NaN  NaN  NaN
34983     820630         Haxe  40281480       NaN  NaN  NaN
34984     820630          C++  33063012       NaN  NaN  NaN
34985     820630          C++  33065618       NaN  NaN  NaN
34986     820630          ASP  33065759       NaN  NaN  NaN
34987     820630           C#  33125189       NaN  NaN  NaN
34988     820630           C#  36723817       NaN  NaN  NaN
34989     820630          ASP  33066494       NaN  NaN  NaN
34990     820630           C#  33066345       NaN  NaN  NaN
34991     820630         Haxe  40826224       NaN  NaN  NaN
34992     820630         Haxe  41461474       NaN  NaN  NaN
34993     820630         Haxe  40869063       NaN  NaN  NaN
34994     820630         Haxe  41891278       NaN  NaN  NaN
34995     820630         Haxe  42716132       NaN  NaN  NaN
34996     820630           C#  33070057       NaN  NaN  NaN
34997     820630          C++  33071493       NaN  NaN  NaN
34998     820630   JavaScript  33058142       NaN  NaN  NaN
34999     820630         Haxe  40068875       NaN  NaN  NaN
35000     820630           C#  33070060       NaN  NaN  NaN
35001     820630         Haxe  40407022       NaN  NaN  NaN
35002     820630           C#  33056999       NaN  NaN  NaN
35003     820630           C#  35728992       NaN  NaN  NaN
35004     820630          C++  33065312       NaN  NaN  NaN
35005     820630          ASP  33066503       NaN  NaN  NaN
35006     820630         GLSL  33066512       NaN  NaN  NaN
35007     820630           C#  32462892       NaN  NaN  NaN
35008     820630           C#  43804652       NaN  NaN  NaN

[28776 rows x 6 columns]

In [162]:
Location_Languages_repos =(Location_Languages_repos.groupby(by=['iso3','language','city'])).count()

In [164]:
Location_Languages_repos.to_csv('users_repos_count.csv',encoding='utf-8')

In [68]:
#Location_Languages_repos=Location_Languages_repos.sort_values(by='Repositories_Count',ascending=False).reset_index(drop=False)

In [69]:
#Location_Languages_repos=Location_Languages_repos.groupby(['language','city','iso2','iso3'])['Repositories_Count',].idxmax()

In [70]:
#Location_Languages_repos=Location_Languages_repos.sort_values(by = 'Repositories_Count',ascending=False)

In [120]:
Location_Languages_repos.to_csv('Location_Languages_repos1.csv')

# 6) Which Projects have highest fork counts  and those Projects used by which Companies and based on which language which will show curosity of users towards particular projects .

In [193]:
frame1 = user_info_location_coordinates[['owners_id','company']]
frame2= users_rep[['owners_id','language','forks_count','id','name']]

In [16]:
d=list(set(frame2['owners_id']))

frame1=frame1[frame1['owners_id'].isin(d)]

Projects_forks_language_company=pd.merge(left=frame2,right=frame1, how='left', left_on='owners_id', right_on='owners_id')

In [17]:
Projects_forks_language_company=Projects_forks_language_company.groupby(['company','id','language','name']).agg({'forks_count':np.count_nonzero})

In [18]:
Projects_forks_language_company=Projects_forks_language_company.sort_values(by='forks_count',ascending=False).reset_index(drop=False)

In [19]:
Projects_forks_language_company.to_csv('/home/shirz/Desktop/Final files for Descriptive/Projects_forks_language_company.csv')

In [20]:
Projects_forks_language_company

,company,id,language,name,forks_count
0,Clock Limited,1962091,C++,dnssd_firefox,6
1,Thousand Eyes Inc.,652623,Python,ProxyChecker,4
2,Facebook,12984615,Objective-C,yubiswitch,4
3,Axion Commerce,3327257,JavaScript,jQuery-Selectable-Table-Rows,4
4,Thousand Eyes Inc.,18611312,C++,json-bechmarks,4
5,Thousand Eyes Inc.,1494466,Java,ayed-practica2,4
6,Facebook,1136775,Perl,perl-monit-http-api,4
7,Fitbit,2516926,JavaScript,TermPaper,4
8,Fitbit,2440262,Objective-C,Pilot,4
9,Simpleweb,3974792,JavaScript,Boxee,4
10,Atlassian,1054082,JavaScript,IKS-Aloha-Editor-Plugins,4
11,Basho Technologies,3714501,Java,drools,3
12,Basho Technologies,4330231,Ruby,omniauth-mhealth,3
13,Tascent,13604452,VHDL,k7_netfpga,3
14,Tascent,8176046,C,ssdma,3
15,Tascent,8175775,Verilog,ahci_mpi,3
16,Tascent,8176074,Verilog,opci,3
17,Tascent,8404023,C,lsa_raid,3
18,Espians,111567,CSS,blog,3
19,Basho Technologies,1683576,JavaScript,randysecrist.github.com,3
20,@imin-ltd,21258068,CSS,prayermate,3
21,Basho Technologies,572078,Java,GEdit,3
22,Independent contractor,67500674,TypeScript,harmonics-explorer,3
23,Tascent,8175601,Verilog,ahci,3
24,@imin-ltd,29888571,Ruby,biblequotes,3
25,Basho Technologies,355955,Python,py-mdns,3
26,Independent contractor,64391875,JavaScript,discreetmusic.js,3
27,Independent contractor,60259684,TypeScript,elseq,3
28,Independent contractor,47824589,JavaScript,angular-phonecat,3
29,Tascent,14441886,C,bladeRF,3
...,...,...,...,...,...
4516,Happy Nerd Shirts,25353919,JavaScript,my-projectA-name,0
4517,HPE,55714074,JavaScript,material2-test,0
4518,HPE,65922578,Java,dropwizard-saml-example,0
4519,HPE,67642079,Java,hawkbit,0
4520,HPE,67945211,Java,hawkbit-external,0
4521,HPE,70347832,Java,hawkbit-demo-ext,0
4522,Happy Nerd Shirts,5902859,Java,radiatorview-plugin,0
4523,Happy Nerd Shirts,7960461,JavaScript,jenky,0
4524,Happy Nerd Shirts,9453020,Ruby,shoulda,0
4525,Happy Nerd Shirts,12217172,Shell,fish,0
4526,Happy Nerd Shirts,13012046,JavaScript,backbone.debug,0
4527,Happy Nerd Shirts,18402448,Ruby,half-pipe,0
4528,Happy Nerd Shirts,19510199,JavaScript,underscore-contrib,0
4529,Happy Nerd Shirts,21818395,JavaScript,underscore.inflection,0
4530,Happy Nerd Shirts,29919658,CSS,githubThemes,0
4531,Heriot Watt University,6793558,JavaScript,galactic-harmony,0
4532,Happy Nerd Shirts,30876454,JavaScript,backbone.viewcache,0
4533,Happy Nerd Shirts,37590512,Ruby,konacha,0
4534,Happy Nerd Shirts,37734469,JavaScript,mocha,0
4535,Happy Nerd Shirts,38318227,Ruby,compass-rails,0
4536,Happy Nerd Shirts,48081623,JavaScript,superstatic-prerender,0
4537,Happy Nerd Shirts,51834368,JavaScript,javascript,0
4538,Happy Nerd Shirts,52359164,JavaScript,babel-preset-es2015-loose,0
4539,Happy Nerd Shirts,59602586,JavaScript,bootstrap-loader,0
4540,Happy Nerd Shirts,61428134,Groovy,SmartThingsPublic,0
4541,Happy Nerd Shirts,68387658,JavaScript,webshim,0
4542,Happy Nerd Shirts,68816641,CSS,bootstrap-flexbox-static,0
4543,Heriot Watt University,6153614,JavaScript,dojos,0
4544,Heriot Watt University,6760356,JavaScript,mamacdon.github.com,0
4545,,68261061,TypeScript,DefinitelyTyped,0